import Head from "next/head";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Schematics 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/header-logo.png" />
      </Head>

      <main>
        <div className="w-screen h-screen bg-dark-primary"></div>
      </main>
    </div>
  );
}
